[package]
name = "csharpbindgen"
version = "0.1.0"
authors = ["Atul Varma <varmaa@gmail.com>"]
edition = "2018"

[dev-dependencies]
insta = "0.8.1"

[dependencies.syn]
version = "0.15"
features = ["full", "extra-traits"]
